name: Unit tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install -r requirements.txt
      - name: Run tox
        # Run tox using the version of Python in `PATH`.
        # Run all tests, except end_to_end_test.py since that test requires
        # logging-in to SmugMug.
        run: tox -e py -- -k 'not end_to_end_test'
